#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v19
# autospec commit: 6a4b23bb3e69
#
Name     : pypi-pyarrow
Version  : 17.0.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/27/4e/ea6d43f324169f8aec0e57569443a38bab4b398d09769ca64f7b4d467de3/pyarrow-17.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/27/4e/ea6d43f324169f8aec0e57569443a38bab4b398d09769ca64f7b4d467de3/pyarrow-17.0.0.tar.gz
Summary  : Python library for Apache Arrow
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-pyarrow-python = %{version}-%{release}
Requires: pypi-pyarrow-python3 = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : libxml2-dev
BuildRequires : llvm-dev
BuildRequires : pkgconfig(arrow)
BuildRequires : pkgconfig(libzstd)
BuildRequires : pkgconfig(python3)
BuildRequires : pypi(arrow)
BuildRequires : pypi(cython)
BuildRequires : pypi(numpy)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi-cython
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<!---
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

%package dev
Summary: dev components for the pypi-pyarrow package.
Group: Development
Provides: pypi-pyarrow-devel = %{version}-%{release}
Requires: pypi-pyarrow = %{version}-%{release}

%description dev
dev components for the pypi-pyarrow package.


%package python
Summary: python components for the pypi-pyarrow package.
Group: Default
Requires: pypi-pyarrow-python3 = %{version}-%{release}

%description python
python components for the pypi-pyarrow package.


%package python3
Summary: python3 components for the pypi-pyarrow package.
Group: Default
Requires: python3-core
Provides: pypi(pyarrow)
Requires: pypi(numpy)

%description python3
python3 components for the pypi-pyarrow package.


%prep
%setup -q -n pyarrow-17.0.0
cd %{_builddir}/pyarrow-17.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726873511
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/accumulation_queue.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/aggregate_node.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/api.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/asof_join_node.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/backpressure_handler.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/benchmark_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/bloom_filter.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/exec_plan.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/hash_join.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/hash_join_dict.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/hash_join_node.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/map_node.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/options.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/order_by_impl.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/partition_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/pch.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/query_context.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/schema_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/task_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/test_nodes.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/time_series_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/tpch_node.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/type_fwd.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/unmaterialized_table.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/acero/visibility.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/api.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/array_base.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/array_binary.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/array_decimal.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/array_dict.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/array_nested.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/array_primitive.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/array_run_end.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/builder_adaptive.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/builder_base.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/builder_binary.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/builder_decimal.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/builder_dict.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/builder_nested.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/builder_primitive.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/builder_run_end.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/builder_time.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/builder_union.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/concatenate.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/data.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/diff.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/array/validate.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/buffer.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/buffer_builder.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/builder.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/c/abi.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/c/bridge.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/c/dlpack.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/c/dlpack_abi.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/c/helpers.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/chunk_resolver.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/chunked_array.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compare.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/api.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/api_aggregate.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/api_scalar.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/api_vector.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/cast.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/exec.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/expression.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/function.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/function_options.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/kernel.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/ordering.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/registry.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/row/grouper.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/type_fwd.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/compute/util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/config.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/csv/api.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/csv/chunker.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/csv/column_builder.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/csv/column_decoder.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/csv/converter.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/csv/invalid_row.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/csv/options.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/csv/parser.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/csv/reader.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/csv/test_common.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/csv/type_fwd.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/csv/writer.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/api.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/dataset.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/dataset_writer.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/discovery.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/file_base.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/file_csv.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/file_ipc.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/file_json.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/file_orc.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/file_parquet.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/parquet_encryption_config.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/partition.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/pch.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/plan.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/projector.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/scanner.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/type_fwd.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/dataset/visibility.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/datum.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/device.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/extension/fixed_shape_tensor.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/extension_type.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/filesystem/api.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/filesystem/azurefs.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/filesystem/filesystem.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/filesystem/filesystem_library.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/filesystem/gcsfs.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/filesystem/hdfs.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/filesystem/localfs.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/filesystem/mockfs.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/filesystem/path_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/filesystem/s3_test_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/filesystem/s3fs.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/filesystem/test_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/filesystem/type_fwd.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/api.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/client.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/client_auth.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/client_cookie_middleware.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/client_middleware.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/client_tracing_middleware.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/middleware.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/otel_logging.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/pch.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/platform.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/server.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/server_auth.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/server_middleware.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/server_tracing_middleware.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/sql/api.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/sql/client.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/sql/column_metadata.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/sql/server.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/sql/server_session_middleware.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/sql/server_session_middleware_factory.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/sql/types.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/sql/visibility.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/test_definitions.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/test_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/transport.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/transport_server.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/type_fwd.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/types.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/types_async.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/flight/visibility.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/integration/json_integration.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/api.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/buffered.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/caching.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/compressed.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/concurrency.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/file.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/hdfs.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/interfaces.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/memory.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/mman.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/slow.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/stdio.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/test_common.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/transform.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/io/type_fwd.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/ipc/api.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/ipc/dictionary.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/ipc/feather.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/ipc/json_simple.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/ipc/message.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/ipc/options.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/ipc/reader.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/ipc/test_common.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/ipc/type_fwd.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/ipc/util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/ipc/writer.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/json/api.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/json/chunked_builder.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/json/chunker.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/json/converter.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/json/object_parser.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/json/object_writer.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/json/options.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/json/parser.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/json/rapidjson_defs.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/json/reader.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/json/test_common.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/json/type_fwd.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/memory_pool.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/memory_pool_test.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/pch.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/pretty_print.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/api.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/arrow_to_pandas.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/async.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/benchmark.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/common.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/csv.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/datetime.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/decimal.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/deserialize.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/extension_type.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/filesystem.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/flight.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/gdb.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/helpers.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/inference.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/init.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/io.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/ipc.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/iterators.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/lib.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/lib_api.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/numpy_convert.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/numpy_interop.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/numpy_to_arrow.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/parquet_encryption.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/pch.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/platform.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/pyarrow.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/pyarrow_api.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/pyarrow_lib.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/python_test.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/python_to_arrow.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/serialize.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/type_traits.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/udf.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/python/visibility.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/record_batch.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/result.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/scalar.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/sparse_tensor.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/status.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/stl.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/stl_allocator.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/stl_iterator.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/table.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/table_builder.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/tensor.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/tensor/converter.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/async_test_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/builder.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/executor_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/extension_type.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/fixed_width_test_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/future_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/generator.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/gtest_compat.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/gtest_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/matchers.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/pch.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/random.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/uniform_real.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/testing/visibility.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/type.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/type_fwd.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/type_traits.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/algorithm.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/align_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/aligned_storage.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/async_generator.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/async_generator_fwd.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/async_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/base64.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/basic_decimal.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/benchmark_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/binary_view_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bit_block_counter.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bit_run_reader.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bit_stream_utils.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bit_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bitmap.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bitmap_builders.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bitmap_generate.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bitmap_ops.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bitmap_reader.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bitmap_visit.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bitmap_writer.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bitset_stack.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bpacking.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bpacking64_default.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bpacking_avx2.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bpacking_avx512.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bpacking_default.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/bpacking_neon.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/byte_size.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/cancel.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/checked_cast.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/compare.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/compression.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/concurrent_map.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/config.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/converter.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/counting_semaphore.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/cpu_info.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/crc32.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/debug.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/decimal.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/delimiting.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/dict_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/dispatch.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/double_conversion.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/endian.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/float16.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/formatting.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/functional.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/future.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/hash_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/hashing.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/int_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/int_util_overflow.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/io_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/iterator.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/key_value_metadata.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/launder.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/list_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/logger.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/logging.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/macros.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/map.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/math_constants.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/memory.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/mutex.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/parallel.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/pcg_random.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/print.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/queue.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/range.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/ree_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/regex.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/rle_encoding.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/rows_to_batches.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/simd.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/small_vector.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/sort.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/spaced.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/span.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/stopwatch.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/string.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/string_builder.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/task_group.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/tdigest.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/test_common.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/thread_pool.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/time.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/tracing.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/trie.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/type_fwd.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/type_traits.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/ubsan.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/union_util.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/unreachable.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/uri.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/utf8.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/value_parsing.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/vector.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/visibility.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/windows_compatibility.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/util/windows_fixup.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/ProducerConsumerQueue.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/datetime.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/datetime/date.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/datetime/ios.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/datetime/tz.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/datetime/tz_private.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/datetime/visibility.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/double-conversion/bignum-dtoa.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/double-conversion/bignum.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/double-conversion/cached-powers.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/double-conversion/diy-fp.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/double-conversion/double-conversion.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/double-conversion/double-to-string.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/double-conversion/fast-dtoa.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/double-conversion/fixed-dtoa.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/double-conversion/ieee.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/double-conversion/string-to-double.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/double-conversion/strtod.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/double-conversion/utils.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/portable-snippets/debug-trap.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/portable-snippets/safe-math.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/strptime.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/xxhash.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/vendored/xxhash/xxhash.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/visit_array_inline.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/visit_data_inline.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/visit_scalar_inline.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/visit_type_inline.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/visitor.h
/usr/lib/python3.12/site-packages/pyarrow/include/arrow/visitor_generate.h

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
